name: aeropost-hello
favicon: null
layout_spectrum: 0.49514
typography_spectrum: 0.8077132697217166
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfdff'
    - '#040500'
    - '#779a00'
    - '#465c1b'
    - '#c8dd95'
  brandStrength: 0.061591545352712274
  lightness: 0.5902694573160261
  saturation: 0.32788254087790847
  rhythmicContrast: 0.8542854783590883
purpose: []
